// <auto-generated />
using System;
using Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250401182612_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Domain.Equipment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            LastUpdated = new DateTime(2025, 4, 3, 12, 30, 0, 0, DateTimeKind.Utc),
                            Name = "Injection Molding Machine",
                            State = 0
                        },
                        new
                        {
                            Id = "2",
                            LastUpdated = new DateTime(2025, 4, 3, 12, 30, 0, 0, DateTimeKind.Utc),
                            Name = "Conveyor Belt",
                            State = 0
                        },
                        new
                        {
                            Id = "3",
                            LastUpdated = new DateTime(2025, 4, 3, 12, 30, 0, 0, DateTimeKind.Utc),
                            Name = "Quality Control Station",
                            State = 0
                        },
                        new
                        {
                            Id = "4",
                            LastUpdated = new DateTime(2025, 4, 3, 12, 30, 0, 0, DateTimeKind.Utc),
                            Name = "Packaging Machine",
                            State = 0
                        });
                });

            modelBuilder.Entity("Api.Domain.HistoricalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NewState")
                        .HasColumnType("integer");

                    b.Property<int>("PreviousState")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("HistoricalRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
